var k1 = "Karate is a martial art developed in the Ryukyu Kingdom. It developed from the indigenous Ryukyuan martial arts (called te 'hand' tii in Okinawan) under the influence of Chinese martial arts, particularly Fujian White Crane. Karate is now predominantly a striking art using punching, kicking, knee strikes, elbow strikes and open-hand techniques such as knife-hands, spear-hands and palm-heel strikes. Historically, and in some modern styles, grappling, throws, joint locks, restraints and vital-point strikes are also taught. A karate practitioner is called a karateka."
var k2 = "The Empire of Japan annexed the Ryukyu Kingdom in 1879. Karate came to mainland Japan in the early 20th century during a time of migration as Ryukyuans, especially from Okinawa, looked for work in the main islands of Japan. It was systematically taught in Japan after the Taishō era of 1912–1926. In 1922, the Japanese Ministry of Education invited Gichin Funakoshi to Tokyo to give a karate demonstration. In 1924, Keio University established the first university karate club in mainland Japan, and by 1932 major Japanese universities had karate clubs. In this era of escalating Japanese militarism, the name was changed from 唐手 ('Chinese hand' or 'Tang hand') to 空手 ('empty hand') – both of which are pronounced karate in Japanese – to indicate that the Japanese wished to develop the combat form in Japanese style. After World War II, Okinawa became (1945) an important United States military site and karate became popular among servicemen stationed there."

var j1="Judo (Japanese: 柔道, Hepburn: Jūdō, lit. 'gentle way') is an unarmed modern Japanese martial art, Olympic sport (since 1964), and the most prominent form of jacket wrestling competed internationally.Judo was created in 1882 by Kanō Jigorō (嘉納 治五郎) as an eclectic martial art, distinguishing itself from its predecessors (primarily Tenjin Shinyo-ryu jujutsu and Kitō-ryū jujutsu) due to an emphasis on 'randori' (乱取り, lit. 'free sparring') instead of 'kata' (pre-arranged forms) alongside its removal of striking and weapon training elements.[3][4][6] Judo rose to prominence for its dominance over established jujutsu schools in tournaments hosted by the Tokyo Metropolitan Police Department (警視庁武術大会, Keishicho Bujutsu Taikai), resulting in its adoption as the department's primary martial art.[4][3] A judo practitioner is called a 'judoka' (柔道家, jūdōka, lit. 'judo performer'), and the judo uniform is called 'judogi' (柔道着, jūdōgi, lit. 'judo attire')."
var j2="The early history of judo is inseparable from its founder, Japanese polymath and educator Kanō Jigorō (嘉納 治五郎, Jigoro Kano, 1860–1938), born Shinnosuke Jigorō (新之助 治五郎, Jigorō Shinnosuke). Kano was born into a relatively affluent family. His father, Jirosaku, was the second son of the head priest of the Shinto Hiyoshi shrine in Shiga Prefecture. He married Sadako Kano, daughter of the owner of Kiku-Masamune sake brewing company and was adopted by the family, changing his name to Kano. He ultimately became an official in the Shogunate government."

var jj1="Jujutsu (Japanese: 柔術 jūjutsu, pronounced [dʑɯꜜːʑɯtsɯ] (listen)), also known as jiu-jitsu and ju-jitsu, is a family of Japanese martial arts and a system of close combat (unarmed or with a minor weapon) that can be used in a defensive or offensive manner to kill or subdue one or more weaponless or armed and armored opponents. Jiu-jitsu dates back to the 1530s and was coined by Hisamori Tenenouchi when he officially established the first jiu-jitsu school in Japan. This form of martial arts uses few or no weapons at all and includes strikes, throws, holds, and paralyzing attacks against the enemy. Jujutsu developed from the warrior class around the 17th century in Japan. It was designed to supplement the swordsmanship of a warrior during combat. A subset of techniques from certain styles of jujutsu were used to develop many modern martial arts and combat sports, such as judo, aikido, sambo, ARB, Brazilian jiu-jitsu, and mixed martial arts. The official date of foundation of Jiu Jitsu is 1530."
var jj2="The written history of Jujutsu first began during the Nara period (c. 710 – c. 794) combining early forms of Sumo and various Japanese martial arts which were used on the battlefield for close combat. The oldest known styles of Jujutsu are, Shinden Fudo-ryū (c. 1130), Tenshin Shōden Katori Shintō-ryū (c. 1447), and Takenouchi-ryū, which was founded in 1530s. Many jujutsu forms also extensively taught parrying and counterattacking long weapons such as swords or spears via a dagger or other small weapons. In contrast to the neighbouring nations of China and Okinawa whose martial arts made greater use of striking techniques, Japanese hand-to-hand combat forms focused heavily upon throwing (including joint-locking throws), immobilizing, joint locks, choking, strangulation, and to lesser extent ground fighting."

var mt1="Muay Thai (Thai: มวยไทย, RTGS: muai thai, pronounced [mūa̯j tʰāj]), sometimes referred to as Thai boxing, is a combat sport that uses stand-up striking along with various clinching techniques. This discipline is known as the 'art of eight limbs', as it is characterised by the combined use of fists, elbows, knees and shins. Muay Thai became widespread internationally in the late 20th to 21st century, when Westernised practitioners from Thailand began competing in kickboxing and mixed-rules matches as well as matches under muay Thai rules around the world. The professional league is governed by The Professional Boxing Association of Thailand (P.A.T), sanctioned by The Sports Authority of Thailand (S.A.T.). Muay Thai is related to other martial art styles such as musti-yuddha, Adimurai, muay Chaiya, muay boran, muay Lao, lethwei and tomoi. A practitioner of muay Thai is known as a nak muay. Western practitioners in Thailand are sometimes called nak muay farang, meaning 'foreign boxer'."
var mt2="The history of muay Thai can be traced at least to the 16th century as a peace-time martial art practised by the soldiers of King Naresuan. An exhibition of muay Thai was observed and reported by Simon de la Loubère, a French diplomat who was sent by King Louis XIV to the Kingdom of Siam in 1687, in his famous work and the Ayutthaya Kingdom Burmese–Siamese War (1765–1767)Muay boran, and therefore muay Thai, was originally called by more generic names such as toi muay or simply muay. As well as being a practical fighting technique for use in actual warfare, muay became a sport in which the opponents fought in front of spectators who went to watch for entertainment. These muay contests gradually became an integral part of local festivals and celebrations, especially those held at temples. Eventually, the previously bare-fisted fighters started wearing lengths of hemp rope around their hands and forearms. This type of match was called muay khat chueak (มวยคาดเชือก)"

$(document).ready(function () {
      $("#t1").tabs();
      $("#k1").text(k1);
      $("#k2").text(k2);

      $("#t2").tabs();
      $("#j1").text(j1);
      $("#j2").text(j2);

      $("#t3").tabs();
      $("#jj1").text(jj1);
      $("#jj2").text(jj2);

      $("#t4").tabs();
      $("#mt1").text(mt1);
      $("#mt2").text(mt2);
    });